/*
 * DateTime.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using DateTime.Standard.Controllers;
using DateTime.Standard.Http.Client;
using DateTime.Standard.Utilities;

namespace DateTime.Standard
{
    public partial class DateTimeClient
    {

        /// <summary>
        /// Singleton access to DateTimeInstance controller
        /// </summary>
        public DateTimeController DateTimeInstance
        {
            get
            {
                return DateTimeController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public DateTimeClient() { }
        #endregion
    }
}